config/routes.rb
Rails.application.routes.draw do

  root to: 'tests#index'

  devise_for :users, path: :gurus, path_name: { sign_in: :login, sign_out: :logout },
              controllers: { sessions: 'users/sessions' }

  get '/users/:id/badges', to: 'users#badges', as: 'user_badges'

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :test_passages, only: [:show, :update] do
    member do
      get :result
      post :gist
    end
  end

  resources :feedback_messages, only: :create
  get 'feedback', to: "feedback_messages#new"

  resources :badges, only: :index

  namespace :admin do

    resources :gists, shallow: true, only: :index

    resources :badges, shallow: true, except: :index

    resources :tests do
      patch :update_inline, on: :member
       
      resources :questions, shallow: true do 
        resources :answers, shallow: true, except: :index
      end
    end
  end

end

app/models/admin.rb
class Admin < User
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  scope :correct, -> { where(correct: true) }

  validates :body, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/badge.rb
class Badge < ApplicationRecord
  has_and_belongs_to_many :users

  validates :title, presence: true, uniqueness: true
  validates :file_name, presence: true
  validates :rule_value, presence: true
  validates :rule_name,  presence: true

end

app/models/badge_criteria_check.rb
class BadgeCriteriaCheck

  class << self

    def check_criterias(user)
      Badge.all.each do |badge|
        case badge.rule_name
          when 'Category' then category_rule(user, badge)
          when 'Level'    then level_rule(user, badge)
          when 'Attempt'  then attempt_rule(user, badge)
        end
      end
    end

    private

    def category_rule(user, badge)
      category = Category.find_by(title: badge.rule_value)
      user.badges.push(badge) if passed_category_rule?(user, category)
    end

    def level_rule(user, badge)
      level = badge.rule_value.to_i 
      user.badges.push(badge) if passed_level_rule?(user, level)
    end

    def attempt_rule(user, badge)
      attempt = badge.rule_value.to_i
      user.badges.push(badge) if passed_attempt_rule?(user, attempt)
    end

    def passed_category_rule?(user, category)
      user.tests.where('category_id=? AND test_passages.success=?', category.id, true)
                      .pluck(:title).uniq.count == Test.for_category(category.title).count
    end

    def passed_level_rule?(user, level)
      user.tests.where('level=? AND test_passages.success=?', level, true)
                      .pluck(:title).uniq.count == Test.for_level(level).count
    end

    def passed_attempt_rule?(user, attempt)
      title = user.test_passages.last.test.title
      user.tests.where('title=? AND test_passages.success=?', title, true).count == attempt
    end

  end

end

app/models/category.rb
class Category < ApplicationRecord
  has_many :tests

  default_scope { order(title: :asc) }

  validates :title, presence: true
end

app/models/feedback_message.rb
class FeedbackMessage < ApplicationRecord

  belongs_to :user

  validates :body, presence: true
  
end

app/models/gist.rb
class Gist < ApplicationRecord
  belongs_to :user
  belongs_to :question
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :answers
  has_many :gists

  validates :body, presence: true
  validates :answers, length: { maximum: 4 }
end

app/models/test.rb
class Test < ApplicationRecord

  has_many :test_passages
  has_many :users, through: :test_passages
  belongs_to :author, class_name: 'User', foreign_key: 'user_id', optional: true
  belongs_to :category
  has_many :questions

  scope :easy, -> { where(level: 0..1) }
  scope :intermediate, -> { where(level: 2..4) }
  scope :hard, -> { where(level: 5..Float::INFINITY) }
  
  scope :for_category, -> (category) { joins(:category).where(categories: { title: category} ) }
  scope :descending, -> { order(title: :desc) }
  scope :for_level, -> (level) { where(level: level) }

  validates :title, presence: true, uniqueness: { scope: :level }
  validates :level, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :timer, numericality: { only_integer: true, greater_than_or_equal_to: 1 }, allow_nil: true 

  def self.tests_by_category(category)
    self.for_category(category).descending
  end

  def questions_amount
    Rails.cache.write("test_#{self.id}", self.questions.count)
  end

end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :before_validation_set_first_question, on: :create
  before_update     :before_update_set_next_question

  def completed?
    current_question.nil?
  end

  def accept!(answer_ids)
    if correct_answer?(answer_ids)
      self.correct_questions += 1 
    end
    save!
  end

  def success!(ratio, user)
    update_column(:success, true) if ratio >= 85

    BadgeCriteriaCheck.check_criterias(user) if self.success
  end

  def stale?(end_time)
    Time.current >= end_time
  end

  private

  def before_validation_set_first_question
    self.current_question = test.questions.first if test.present?
  end

  def before_update_set_next_question
    self.current_question = test.questions.order(:id).where('id > ?', current_question.id).first
  end

  def correct_answer?(answer_ids)
    correct_answers_count = correct_answers.count

    (correct_answers_count == correct_answers.where(id: answer_ids).count) &&
    correct_answers_count == answer_ids.count
  end

  def correct_answers
    current_question.answers.correct
  end

end

app/models/user.rb
class User < ApplicationRecord

  devise  :database_authenticatable, 
          :registerable,
          :recoverable,
          :rememberable,
          :trackable, 
          :validatable,
          :confirmable

  validates :first_name, presence: true
  validates :last_name, presence: true

  has_many :test_passages
  has_many :tests, through: :test_passages
  has_many :authored_tests, class_name: 'Test'
  has_many :gists
  has_many :feedback_messages
  has_and_belongs_to_many :badges

  def test_passage(test)
    test_passages.order(id: :desc).find_by(test_id: test.id)  
  end

  def admin?
    self.is_a? Admin
  end

  def full_name
    "#{self.first_name} #{self.last_name}"
  end
  
end

app/controllers/tests_controller.rb
class TestsController < ApplicationController

  before_action :authenticate_user!
  before_action :find_test, only: :start

  def index
    @tests = Test.all
  end

  def start
    current_user.tests.push(@test)
    redirect_to current_user.test_passage(@test)

    @test.questions_amount

    if @test.timer
      session["passage_#{current_user.test_passage(@test).id}"] = @test.timer.minutes.from_now
    end
    
  end

  private

  def find_test
    @test = Test.find(params[:id])
  end

end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  BOOTSTRAP_FLASH_CLASS = { 'notice' => 'alert alert-info', 'alert' => 'alert alert-danger' }

  def current_year
    Date.current.year
  end

  def github_url(username, repo)
    link_to "https://github.com/#{username}/#{repo}", target: "_blank" do
      yield
    end
  end

  def flash_message
    flash.map do |type, message|
      content_tag :div, message.html_safe, class: "#{BOOTSTRAP_FLASH_CLASS[type]}" 
    end.join.html_safe
  end

end

app/helpers/badges_helper.rb
module BadgesHelper
end

app/helpers/gists_helper.rb
module GistsHelper

  def question_link(gist)  
    link_to "#{truncate(question.body, length: 25)}", admin_question_path(gist.question)
  end

  def gist_hash_link(gist)
    link_to 'Gist Hash', gist.gist_url
  end

end

app/helpers/questions_helper.rb
module QuestionsHelper
  def question_header(test)
    if test.questions.last.new_record?
      "Create new #{test.title} question"
    else
      "Edit #{test.title} question"
    end
  end
end

app/helpers/tests_helper.rb
module TestsHelper
  TEST_LEVELS = { 0 => :easy, 1 => :elementary, 2 => :advanced, 3 => :hard }.freeze

  def test_level(test)
    TEST_LEVELS[test.level] || :hero
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/_nav.html.erb
<nav class="navbar navbar-dark bg-dark">

  <%= link_to 'TestGuru', admin_tests_path, class: "navbar-brand" %>

  <span class="text-center text-white">
    <b><%= t('.header') %></b>
  </span>

  <div class="text-right">
    <span class="text-white">
      <%= t('.greeting') %>, <b><%= current_user.email %></b> Guru 
    </span>
    <%= link_to t('.logout'), destroy_user_session_path, method: :delete, class: "btn btn-primary" %>
  </div>
  
</nav>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title> Admin Panel |TestGuru </title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render 'admin/nav' %>

    <%= flash_message %>

    <%= yield %>

    <%= render 'shared/footer' %>    
        
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>TestGuru</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/header_navigation' %>

    <div class="container">
      <%= flash_message %>
      <%= yield %>
    </div>

    <%= render 'shared/badge_links' %>

    <%= render 'shared/footer' %>    
  </body>
</html>

app/views/shared/_badge_links.html.erb
<% if user_signed_in? %>

  <p> <%= link_to 'All Badges', badges_path %> </p>

  <p> <%= link_to 'My Badges', user_badges_path(current_user) %> </p> 
     
<% end %>    

app/views/shared/_errors.html.erb
<% if resource.present? && resource.errors.present? %>
  <%= content_tag :div, class: 'resource-errors', data: { resource_id: resource.id } do %>
    <h2>
     <%= t('.header', count: resource.errors.count) %> : 
     </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li> <%= message %> </li>
      <% end %>
    </ul>
  <% end %>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">

  <p>
    Test Guru is web application that allows users check their knowledge by passing tests.
    Every user can create his own test and let others pass it. Result of each test can be
    published in social networks.
  </p>

  <p> <%= current_year %>,
      Kirill Sazonov,
      <%= github_url('kirster','test-guru'){'Test Guru app'} %> 
  </p>

  <p>
    <%= link_to 'Educational project of Thinkentica online-school',
                'http://thinknetica.com/', target: "_blank"  %> 
  </p>

</footer>

app/views/shared/_general_nav.html.erb
<span class="navbar-text">

  <%= content_tag :p do
    concat link_to 'SignUp  ', new_user_registration_path
    concat link_to 'Login',    new_user_session_path
  end %>
  
</span>  

app/views/shared/_header_navigation.html.erb
<nav class="navbar navbar-light bd-light">

  <%= link_to 'Test Guru', root_path, class: "navbar-brand" %>

  <% if user_signed_in? %>
    <%= render 'shared/logged_nav' %>
  <% else %>
    <%= render 'shared/general_nav' %>
  <% end %>    

</nav>

app/views/shared/_logged_nav.html.erb
<% if current_user.admin? %>
  <%= content_tag :span do
    concat link_to t('admin_panel'), admin_tests_path, class: "btn btn-primary" 
  end %>
<% end %>

<span class="navbar-text">

  <%= content_tag :span do
    concat 'Welcome, '
    concat content_tag :b, current_user.first_name
    concat ' Guru '
  end %>

  <%= content_tag :p do
    concat link_to 'Logout', destroy_user_session_path, method: :delete
  end %>

</span>

app/views/shared/_progress_bar.html.erb
<progress max="100" value="0" class="progress-bar" 
          data-questions="<%= Rails.cache.read("test_#{@test_passage.test.id}") %>"
          data-question-index="<%= current_question(@test_passage) %>">
</progress>

app/views/shared/_timer.html.erb
<div class="timer" data-end-time= "<%= session["passage_#{@test_passage.id}"] %>"
                   data-passage-id = "<%= @test_passage.id %>" >

  <span class="minutes"></span>  
  <strong> minutes </strong>
  <span class="seconds"></span>
  <strong> seconds </strong>

</div>