config/routes.rb
Rails.application.routes.draw do

  root to: 'tests#index'

  devise_for :users, path: :gurus, path_name: { sign_in: :login, sign_out: :logout },
              controllers: { sessions: 'users/sessions' }

  get '/users/:id/badges', to: 'users#badges', as: 'user_badges'

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :test_passages, only: [:show, :update] do
    member do
      get :result
      post :gist
    end
  end

  resources :feedback_messages, only: :create
  get 'feedback', to: "feedback_messages#new"

  resources :badges, only: :index

  namespace :admin do

    resources :gists, shallow: true, only: :index

    resources :badges, shallow: true, except: :index

    resources :tests do
      patch :update_inline, on: :member
       
      resources :questions, shallow: true do 
        resources :answers, shallow: true, except: :index
      end
    end
  end

end

app/models/badge.rb
class Badge < ApplicationRecord
  has_and_belongs_to_many :users

  validates :title, presence: true, uniqueness: true
  validates :file_name, presence: true
  validates :rule_value, presence: true
  validates :rule_name,  presence: true

end

app/controllers/admin/badges_controller.rb
class Admin::BadgesController < Admin::BaseController

  before_action :find_badge, only: [:show, :edit, :update, :destroy]

  def new
    @badge = Badge.new    
  end

  def create
    @badge = Badge.new(badge_params)

    if @badge.save
      redirect_to admin_badge_path(@badge), notice: 'Badge successfully created'
    else
      render :new
    end
  end

  def show; end

  def edit; end

  def update
    if @badge.update(badge_params)
      redirect_to admin_badge_path(@badge), notice: 'Badge successfully updated'
    else
      render :edit
    end
  end

  def destroy
    @badge.destroy
    redirect_to badges_path, notice: 'Badge successfully deleted'
  end

  private

  def badge_params
    params.require(:badge).permit(:title, :file_name, :rule_name, :rule_value)  
  end

  def find_badge
    @badge = Badge.find(params[:id])
  end

end

app/controllers/badges_controller.rb
class BadgesController < ApplicationController

  before_action :authenticate_user!
  before_action :find_badges

  def index; end

  private

  def find_badges
    @badges = Badge.all
  end

end

app/helpers/badges_helper.rb
module BadgesHelper
end

app/views/badges/_badge.html.erb
<tr>
  <td class="align-middle"> <%= badge.title %> </td>

  <td class="align-middle"> <%= badge.file_name %> </td>

  <td class="align-middle"> <%= badge.rule_name %> </td>

  <td class="align-middle"> <%= badge.rule_value %> </td>

  <% if current_user.admin? %>

    <td class="align-middle"> <%= link_to 'Show',   admin_badge_path(badge) %> </td>
    <td class="align-middle"> <%= link_to 'Edit',   edit_admin_badge_path(badge) %> </td>
    <td class="align-middle"> <%= link_to 'Delete', admin_badge_path(badge), 
                                                    method: :delete,
                                                    data: { confirm: t('.warning') } %> 
    </td>

  <% end %>
  
</tr>

app/views/badges/index.html.erb
<h1> All badges </h1>

<table class="table mt-3">

  <thead class="thead-dark">

    <tr class="text-center">
      <th scope="col"> Title </th>
      <th scope="col"> File name </th>
      <th scope="col"> Rule </th>
      <th scope="col"> Rule value </th>
      <% if current_user.admin? %>
        <th scope="col" colspan="3"> Actions </th>
      <% end %>
    </tr>

  </thead >

  <%= render @badges %>

</table>

<% if current_user.admin? %>
    <td class="align-middle"> <%= link_to 'New Badge', new_admin_badge_path %> </td>
<% end %>